language: python

env:
  global:
    - DEPS="hyperspy pyxem"
#    - TEST_DEPS="pytest pytest-cov coveralls"

matrix:
  include:
    - env: export PYTHON=3.7

sudo: True # for Miniconda

before_install:
  # Install Miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    hash -r
  # Setup environment
  - source $HOME/miniconda/bin/activate root;
    conda update --yes conda;
    conda config --append channels conda-forge;
    conda create --name testenv --yes python=$PYTHON;
    conda activate testenv
  - conda info -a
  - df -h

install:
  - conda install --yes $DEPS #$TEST_DEPS;
  - pip install .

script:
  - export MPLBACKEND=Agg
#  - pytest --pyargs kikuchipy --cov=kikuchipy

after_success:
  -coveralls
