name: Perhaps make a tagged release

# Trigger workflow when commits to the main branch contain a change in the
# kikuchipy/release.py file. This is because this workflow should only run when a
# tagged release draft is to be made.
on:
  push:
    branches:
      - main
    paths:
      - "kikuchipy/release.py"

jobs:
  make-tagged-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ runner.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install outdated
    - name: Check whether a tagged release draft should be made
      run: |
        cd .github/workflows
        eval x=($(python perhaps_make_tagged_release_draft.py))
        echo "MAKE_RELEASE=${x[0]}" >> $GITHUB_ENV
        echo "PYPI_VERSION=${x[1]}" >> $GITHUB_ENV
        echo "BRANCH_VERSION=${x[2]}" >> $GITHUB_ENV
    - name: Make tagged release draft
      if: ${{ env.MAKE_RELEASE == 'true' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: v${{ env.BRANCH_VERSION }}
        release_name: kikuchipy ${{ env.BRANCH_VERSION }}
        commitish: main
        body: |
          kikuchipy is an open-source Python library for processing and analysis of electron backscatter diffraction (EBSD) patterns.

          See the [changelog](https://kikuchipy.org/en/latest/changelog.html) for all updates from the previous release.
        prerelease: false
